project:
  type: website

website:
  page-navigation: true
  title: "SoCal RUG"
  description: "Southern California R Users Group"
  site-url: "https://socalr.org/"

  repo-url: https://github.com/socalrug/socalr.org

  open-graph: true

  twitter-card:
    creator: "@oc_rug"
    image: "images/SoCal_RUG_logo.png"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Southern California R Users Group"
    background: "#CEDDFB"

  sidebar:
    background: "#CEDDFB"
    logo: "images/SoCal_RUG_Hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/socalrug
        text: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/company/socalrug/
        text: LinkedIn
      - icon: twitter
        href: https://twitter.com/oc_rug
        text: "Twitter: @oc_rug"
      - icon: envelope
        href: "mailto:orangecounty.rug@gmail.com"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "About"
        contents:
          - href: index.qmd
            text: Events Archive
          - href: https://www.meetup.com/socal-rug/
            text: Join our Meetups
          - href: https://github.com/socalrug/presentations
            text: Past Presentations
          - href: "mailto:orangecounty.rug@gmail.com"
            text: Contact Us 
      - section: "Hackathons"
        contents:
          - href: https://github.com/socalrug/hackathon-2022-04
            text: Apr 2022
          - href: https://github.com/socalrug/hackathon-2021-04
            text: Apr 2021
          - href: https://github.com/socalrug/hackathon-2020-04
            text: Apr 2020
          - href: https://github.com/socalrug/hackathon-2019-11
            text: Nov 2019
          - href: https://github.com/socalrug/hackathon-2019-05
            text: May 2019
      - section: "2022 Workshops"
        contents:
          - href: https://www.meetup.com/socal-rug/events/289510286/
            text: Portfolio Building
          - href: https://github.com/socalrug/advanced_regression_2022-10-01
            text: Advanced Regressions
          - href: https://github.com/socalrug/msba-python-workshop-2022-07
            text: Intro to Python
          - href: https://github.com/socalrug/nonparametric_analysis_2022-01-22
            text: Nonparametric Analysis

format:
  html:
    theme: theme.scss
    mainfont: "Montserrat"
    code-copy: true
    code-overflow: wrap
    toc: true
