project:
  type: website

website:
  page-navigation: true
  title: "SoCal RUG"
  description: "Southern California R Users Group"
  site-url: "https://socalr.org/"

  repo-url: https://github.com/socalrug/socalr.org

  open-graph: true

  twitter-card:
    creator: "@oc_rug"
    image: "images/SoCal_RUG_logo.png"

  page-footer:
    left: "&copy; Copyright 2023, Southern California R Users Group"
    background: "#CEDDFB"

  sidebar:
    background: "#CEDDFB"
    logo: "images/SoCal_RUG_Hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/socalrug
        text: GitHub
      - icon: slack
        href: https://socalrug.slack.com/
        text: Slack
      - icon: linkedin
        href: https://www.linkedin.com/company/socalrug/
        text: LinkedIn
      - icon: twitter
        href: https://twitter.com/oc_rug
        text: "Twitter: @oc_rug"
      - icon: instagram
        href: https://www.instagram.com/socalrug/
        text: "Instagram: @socalrug"
      - icon: youtube
        href: https://www.youtube.com/@SouthernCaliforniaRUsersGroup
        text: YouTube
      - icon: envelope
        href: "mailto:orangecounty.rug@gmail.com"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Events Archive
      - href: code_of_conduct.qmd
        text: Code of Conduct
      - text: '<a href="https://www.meetup.com/socal-rug/" target="_blank">Join our Meetups</a>'
      - text: '<a href="https://github.com/socalrug/presentations" target="_blank">Past Presentations</a>'
      - text: '<a href="mailto:orangecounty.rug@gmail.com" target="_blank">Contact Us</a>'
      - section: "Hackathons"
        contents:
          - text: '<a href="https://github.com/socalrug/hackathon-2022-04" target="_blank">Apr 2022</a>'
          - text: '<a href="https://github.com/socalrug/hackathon-2021-04" target="_blank">Apr 2021</a>'
          - text: '<a href="https://github.com/socalrug/hackathon-2020-04" target="_blank">Apr 2020</a>'
          - text: '<a href="https://github.com/socalrug/hackathon-2019-11" target="_blank">Nov 2019</a>'
          - text: '<a href="https://github.com/socalrug/hackathon-2019-05" target="_blank">May 2019</a>'
      - section: "Book Clubs"
        contents:
          - text: '<a href="https://www.meetup.com/socal-rug/events/290821300/" target="_blank">2023-01: Advanced Probabilistic ML</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/284913426/" target="_blank">2022-04: Forecasting Principles and Practice</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/283044538/" target="_blank">2022-01: Information Rules</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/280319522/" target="_blank">2021-09: Introduction to Statistical Learning</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/278765369/" target="_blank">2021-07: OpenIntro Statistics</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/278831056/" target="_blank">2021-07: Communicating with Data</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/276575373/" target="_blank">2021-03: Text Mining with R</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/275783285/" target="_blank">2021-02: Mastering Spark with R</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/275719547/" target="_blank">2021-01: R for Data Science</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/272034792/" target="_blank">2020-09: Advanced R</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/270076542/" target="_blank">2020-05: Applied Predictive Modeling</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/268226879/" target="_blank">2020-02: Feature Engineering & Selection</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/266912350/" target="_blank">2020-01: R for Data Science</a>'
      - section: "2023 Workshops"
        contents:
          - text: '<a href="https://www.meetup.com/socal-rug/events/290969003/" target="_blank">Introduction to Stochastic Processes</a>'
      - section: "2022 Workshops"
        contents:
          - text: '<a href="https://www.meetup.com/socal-rug/events/289510286/" target="_blank">Portfolio Building</a>'
          - text: '<a href="https://github.com/socalrug/advanced_regression_2022-10-01" target="_blank">Advanced Regressions</a>'
          - text: '<a href="https://github.com/socalrug/msba-python-workshop-2022-07" target="_blank">Intro to Python</a>'
          - text: '<a href="https://github.com/socalrug/nonparametric_analysis_2022-01-22" target="_blank">Nonparametric Analysis</a>'
      - section: "2021 Workshops"
        contents:
          - text: '<a href="https://www.meetup.com/socal-rug/events/281984572/" target="_blank">Portfolio Building</a>'
          - text: '<a href="https://github.com/socalrug/regression_models_2021-02-09" target="_blank">Modeling Normally Distributed Data with Repeated Measures</a>'
      - section: "2020 Workshops"
        contents:
          - text: '<a href="https://www.meetup.com/socal-rug/events/274071838/" target="_blank">Portfolio Building</a>'
          - text: '<a href="https://github.com/socalrug/regression_models_2020-10-13" target="_blank">Regression Models with R Applications</a>'
          - text: '<a href="https://github.com/socalrug/msba-python-workshop-2020-07" target="_blank">Intro to Python</a>'


format:
  html:
    theme: theme.scss
    fontsize: 1.0em
    mainfont: "Montserrat"
    code-copy: true
    code-overflow: wrap
    toc: true
    link-external-newwindow: true
