name: Render and Deploy socalr.org
'on':  
  push:
    branches:
      - master
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install Package Dependencies
        run: |-
          options(repos = 'https://packagemanager.rstudio.com/all/latest')
          install.packages('renv')
          renv::restore()
        shell: Rscript {0}  
      - name: Render Site
        env:
          LAOCRUG_TOKEN: ${{ secrets.LAOCRUG_TOKEN }}
          GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
        run: |-
          # source(here::here('R', 'download_events.R'))
          rmarkdown::render('events.Rmd')
          distill:::render_website(dir = '.', 'website')
        shell: Rscript {0}
        
      - name: Install npm
        uses: actions/setup-node@v1

      - name: Deploy to Netlify
        # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install netlify-cli -g
          netlify deploy --prod

