name: Render and Deploy socalr.org (distill)
'on':  
  push:
    branches:
      - master
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: Render Site
        env:
          LAOCRUG_TOKEN: ${{ secrets.LAOCRUG_TOKEN }}
          GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
        run: |-
          Rscript -e "source(here::here('R', 'download_events.R'))" \
                  -e "distill:::render_website(dir = '.', 'website')" \
                  -e "rmarkdown::render('welcome/index.Rmd')"
          echo "::set-env name=DEPLOY_PATH::$(Rscript -e "cat(rmarkdown::site_config()[['output_dir']])")"
      - name: Deploy to Netlify
        if: github.ref == 'refs/heads/master'
        uses: netlify/actions/cli@645ae7398cf5b912a3fa1eb0b88618301aaa85d0
        with:
          args: deploy --dir=$DEPLOY_PATH --prod --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    container: rocker/verse:latest
